version: '3'
services:
  db:
    restart: always
    image: mysql:5.7
    command: "--innodb_use_native_aio=0"
    environment: 
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: RR
    ports:
      - '3307:3306'
    volumes: 
      - ./docker/data/db:/var/lib/mysql
  app:
    env_file: .env 
    build: .
    ports:
      - '3001:3001'
    depends_on:
      - db